Runtime :
  outpath : /u/ki/jderose/desims/BCC/Chinchilla/Herd/Chinchilla-0/pyaddgals/Buzzard-0_full
NBody :
  Domain :
    fmt : BCCLightcone
    lbox : [1050, 2600, 4000]
    rmin : [1.0, 900, 2250]
    rmax : [900, 2250, 3950]
    nrbins : [2,5,5]
    nside : 4
    nest : True
  partpath :
    - /u/ki/jderose/desims/BCC/Chinchilla/Herd/Chinchilla-0/Lb1050/output/pixlc/
    - /u/ki/jderose/desims/BCC/Chinchilla/Herd/Chinchilla-0/Lb2600/output/pixlc/
    - /u/ki/jderose/desims/BCC/Chinchilla/Herd/Chinchilla-0/Lb4000/output/pixlc/
  denspath :
    - /u/ki/jderose/desims/BCC/Chinchilla/Herd/Chinchilla-0/Lb1050/output/calcrnn/
    - /u/ki/jderose/desims/BCC/Chinchilla/Herd/Chinchilla-0/Lb2600/output/calcrnn/
    - /u/ki/jderose/desims/BCC/Chinchilla/Herd/Chinchilla-0/Lb4000/output/calcrnn/
  hinfopath :
    - /u/ki/jderose/desims/BCC/Chinchilla/Herd/Chinchilla-0/Lb1050/output/pixlc/
    - /u/ki/jderose/desims/BCC/Chinchilla/Herd/Chinchilla-0/Lb2600/output/pixlc/
    - /u/ki/jderose/desims/BCC/Chinchilla/Herd/Chinchilla-0/Lb4000/output/pixlc/
  halofile :
    - /u/ki/jderose/desims/BCC/Chinchilla/Herd/Chinchilla-0/Lb1050/output/halos/cut_reform_out_0.parents
    - /u/ki/jderose/desims/BCC/Chinchilla/Herd/Chinchilla-0/Lb2600/output/halos/cut_reform_out_0.parents
    - /u/ki/jderose/desims/BCC/Chinchilla/Herd/Chinchilla-0/Lb4000/output/halos/cut_reform_out_0.parents
  halodensfile :
    - /u/ki/jderose/desims/BCC/Chinchilla/Herd/Chinchilla-0/Lb1050/output/halos/rnn_cut_reform_out_0.parents
    - /u/ki/jderose/desims/BCC/Chinchilla/Herd/Chinchilla-0/Lb2600/output/halos/rnn_cut_reform_out_0.parents
    - /u/ki/jderose/desims/BCC/Chinchilla/Herd/Chinchilla-0/Lb4000/output/halos/rnn_cut_reform_out_0.parents

Cosmology:
  omega_m : 0.286
  omega_b : 0.046
  h : 1.0
  n_s : 0.96
  sigma8 : 0.82
  w : -1.0

GalaxyModel :
  ADDGALSModel :
    luminosityFunctionConfig :
      modeltype : DSGLuminosityFunction
      magmin : 25.0
    rdelModelConfig :
      rdelModelFile : /u/ki/jderose/ki23/SkyFactory-config/Addgals/rdel/DSG_0.684_0.17_global_rdelmodel.txt
      lcenModelFile : /u/ki/jderose/ki23/SkyFactory-config/Addgals/rdel/C400_DSG_0.684_0.17_lcenmass.fits
      lcenMassMin : [3162277660168, 3162277660168, 10000000000000]
      useSubhalos : False
      scatter: 0.17
    colorModelConfig :
      redFractionModelFile : /u/ki/jderose/ki23/SkyFactory-config/Addgals/primus_rf_model.txt
      trainingSetFile : /u/ki/jderose/ki23/SkyFactory-config/Addgals/sdss_vagc_kcorr_r177_z02_wdens.fits
      filters :
        - desy3/desy3std_g.par
        - desy3/desy3std_r.par
        - desy3/desy3std_i.par
        - desy3/desy3std_z.par
        - desy3/desy3_Y.par
      band_shift : 0.1
